version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web

  api:
    image: despotov/dbert:latest
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  web:
    image: despotov/dbert-ui:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8001
