from src.schemas import Entity


mocked_entities = \
 [{'end': 45,
   'entity_type': 'B-MISC',
   'index': 7,
   'start': 36,
   'text': 'Framework'},
  {'end': 48,
   'entity_type': 'I-MISC',
   'index': 8,
   'start': 46,
   'text': '13'},
  {'end': 84,
   'entity_type': 'B-ORG',
   'index': 20,
   'start': 82,
   'text': 'EC'},
  {'end': 156,
   'entity_type': 'B-MISC',
   'index': 35,
   'start': 150,
   'text': 'Google'},
  {'end': 159,
   'entity_type': 'I-MISC',
   'index': 36,
   'start': 157,
   'text': 'Ch'},
  {'end': 163,
   'entity_type': 'I-MISC',
   'index': 37,
   'start': 159,
   'text': 'rome'},
  {'end': 167,
   'entity_type': 'I-MISC',
   'index': 38,
   'start': 163,
   'text': 'book'}]

mocked_ner_results = [
    {'entity': 'B-MISC',
     'score': 0.99106884,
     'index': 7,
     'word': 'Framework',
     'start': 36,
     'end': 45},
    {'entity': 'I-MISC',
     'score': 0.9755324,
     'index': 8,
     'word': '13',
     'start': 46,
     'end': 48},
    {'entity': 'B-ORG',
     'score': 0.70980257,
     'index': 20,
     'word': 'EC',
     'start': 82,
     'end': 84},
    {'entity': 'B-MISC',
     'score': 0.92365795,
     'index': 35,
     'word': 'Google',
     'start': 150,
     'end': 156},
    {'entity': 'I-MISC',
     'score': 0.8950261,
     'index': 36,
     'word': 'Ch',
     'start': 157,
     'end': 159},
    {'entity': 'I-MISC',
     'score': 0.8735458,
     'index': 37,
     'word': '##rome',
     'start': 159,
     'end': 163},
    {'entity': 'I-MISC',
     'score': 0.8423008,
     'index': 38,
     'word': '##book',
     'start': 163,
     'end': 167}]

consecutive_entities = \
 [Entity(text='Ch', entity_type='B-MISC', index=36, start=157, end=159),
  Entity(text='rome', entity_type='I-MISC', index=37, start=159, end=163),
  Entity(text='book', entity_type='I-MISC', index=38, start=163, end=167)]
